update lei set lei_nome = "Constituição 1988" where id = 1;
update lei set lei_nome = "Lei 5869/1973 - Código de Processo Civil" where id = 2;
update lei set lei_nome = "Regimento Interno" where id = 3;
update lei set lei_nome = "Súmula 282 - Inadmissão de RE", lei_descricao = "Inadmissão de REs não pré-questionados" where id = 4;
update lei set lei_nome = "Súmula 279 - Inadmissão de RE", lei_descricao = "Inadmissão de REs para reexame de prova" where id = 5;
update lei set lei_nome = "Súmula 356 - Inadmissão de RE", lei_descricao = "Inadmissão de REs sem prévio embargo declaratório" where id = 6;
update lei set lei_nome = "Lei 8038/1990 - Procedimentos STF", lei_descricao = "Leis dos procedimentos junto ao STF e STJ" where id = 7;
update lei set lei_nome = "Lei 8213/1991 - Previdência Social", lei_descricao = "Dispõe sobre os Planos de Benefícios da Previdência Social" where id = 8;
update lei set lei_nome = "Decreto-Lei 2848/1940 - Código Penal" where id = 9;
update lei set lei_nome = "Decreto-Lei 3689/1941 - Código de Processo Penal" where id = 10;
update lei set lei_nome = "Súmula 288 - Inadmissão de Agravo em RE", lei_descricao = "Nega seguimento de Agravo em RE por falta de documentos" where id = 11;
update lei set lei_nome = "Lei 9032/1995 Salário Mínimo e Previdência" where id = 12;
update lei set lei_nome = "Súmula 280 - Inadmissão de RE", lei_descricao = "Inadmissão de RE por ofensa a direito local" where id = 13;
update lei set lei_nome = "Lei 7787/1989 - Custeio da Previdência Social" where id = 14;
update lei set lei_nome = "Constituição 1969" where id = 15;
update lei set lei_nome = "Emenda 20/1998 - Previdência Social" where id = 16;
update lei set lei_nome = "Lei 8212/1991 - Custeio da Seguridade Social" where id = 17;
update lei set lei_nome = "Lei 9756/1998 - Recursos aos Tribunais" where id = 18;
update lei set lei_nome = "Lei 5172/1966 - Código Tributário Nacional" where id = 19;
update lei set lei_nome = "Decreto 5452/1943 - Consolidação das Leis do Trabalho" where id = 20;
